name: Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
#learning docker 
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
          - uses: actions/checkout@v3

          # Runs a single command using the runners shell
          - name: Run a one-line script
            run: echo Hello, world!

          # Runs a set of commands using the runners shell
          - name: Run a multi-line script
            run: |
              echo Add other actions to build,
              echo test, and deploy your project.
  Windows:
    runs-on: windows-latest
    steps:
          - uses: actions/checkout@v3

          # Runs a single command using the runners shell
          - name: Run a one-line script
            run: echo Hello, world!

          # Runs a set of commands using the runners shell
          - name: Run a multi-line script
            run: |
              echo Add other actions to build,
              echo test, and deploy your project.
  Mac:
    runs-on: macos-latest
    steps:
      - run: date
        
  
  depends:
    needs: [ubuntu, Windows]
    runs-on: ubuntu-latest
    steps:
          # Runs a single command using the runners shell
          - name: Run a one-line script
            run: echo Hello, world!
